name: Build and publish to mfinn.de

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ftp_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - run: npm ci
    - run: npm run build-only
    - uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: mfinn.de
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /